export * from "./templates/appearance-research.js";
export * from "./templates/character-creation.js";
export * from "./templates/sprite-from-appearance.js";
export * from "./templates/hatch-pet.js";
export * from "./templates/system-prompt.js";
export * from "./templates/profile-extraction.js";
export * from "./templates/research-agents.js";
export * from "./templates/framework-synthesis.js";
export * from "./templates/voice-test.js";
